console.time("Your code took")
console.log("Hello console")
console.log(4*4)
console.log(34)
console.log(true)
console.log([34,2,1,2])
console.log({branch:"IT",marks:84})
console.table({branch:"IT",marks:84})
console.warn("this is warn")
// console.clear()
console.timeEnd("Your code took")
console.assert(566<189,"Age >189 is not possible")
console.error("This is an error");